name: Release

on:
    push:
        tags:
            - "v*.*.*"

env:
    CARGO_TERM_COLOR: always

jobs:
    build_matrix:
        strategy:
            matrix:
                platform:
                    - name: Windows
                      os: windows-latest
                      target: x86_64-pc-windows-msvc
                    - name: GNU Linux
                      os: ubuntu-latest
                      target: x86_64-unknown-linux-gnu
                    - name: MacOS aarch64
                      os: macos-latest
                      target: aarch64-apple-darwin
        runs-on: ${{ matrix.platform.os }}

        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Install Rust
              uses: actions-rust-lang/setup-rust-toolchain@v1
            - name: Build
              run: cargo build --release
            - name: Rename Windows
              if: contains(matrix.platform.target, 'windows')
              run: |
                cd target/release
                move arrayniac.exe arrayniac-${{matrix.platform.taret}}.exe
                cd ../..
            - name: Rename
              if: ${{ !contains(matrix.platform.target, 'windows') }}
              run: |
                cd target/release
                mv arrayniac arrayniac-${{matrix.platform.taret}}
                cd ../..
            - name: Upload artifact
              uses: actions/upload-artifact@v4
              with:
                name: arrayniac-${{matrix.platform.target}}${{ contains(matrix.platform.target, 'windows') && '.exe' || '' }}
                path: target/release/arrayniac-${{matrix.platform.target}}${{ contains(matrix.platform.target, 'windows') && '.exe' || '' }}
                overwrite: true
                retention-days: 1


    release:
        permissions:
            contents: write
        needs: [build_matrix]
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Download artifacts
              uses: actions/download-artifact@v4
              with:
                path: ${{github.workspace}}/artifacts
            - name: Release
              uses: softprops/action-gh-release@v2
              with:
                files: |
                  ${{github.workspace}}/artifacts/*/*
