name: Release

on:
    push:
        tags:
            - "v*.*.*"

env:
    CARGO_TERM_COLOR: always

jobs:
    build_matrix:
        strategy:
            matrix:
                platform:
                    - name: Windows
                      os: windows-latest
                      target: x86_64-pc-windows-msvc
                    - name: GNU Linux
                      os: ubuntu-latest
                      target: x86_64-unknown-linux-gnu
                    - name: MacOS x64
                      os: macos-latest
                      target: x86_64-apple-darwin
                    - name: MacOS ARM64
                      os: macos-latest
                      target: aarch64-apple-darwin
        runs-on: ${{ matrix.platform.os }}

        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Remove Cargo config
              if: ${{ !contains(matrix.platform.target, 'windows') }}
              run: rm .cargo/config.toml
            - name: Remove Cargo Windows
              if: ${{ contains(matrix.platform.target, 'windows') }}
              run: del .cargo/config.toml
            - name: Install Rust
              uses: actions-rust-lang/setup-rust-toolchain@v1
            - name: Apple add cross-compilation target
              if: ${{ matrix.platform.target == 'x86_64-apple-darwin' }}
              run: rustup target add ${{ matrix.platform.target }}
            - name: Build
              run: cargo build ${{ format('--target {0}', matrix.platform.target) }} --release
            - name: Move executable
              if: ${{ !contains(matrix.platform.target, 'windows') }}
              run: |
                mv target/${{ matrix.platform.target }}/release/arrayniac target/release
            - name: Move executable Windows
              if: contains(matrix.platform.target, 'windows')
              run: |
                move target/${{ matrix.platform.target }}/release/arrayniac.exe target/release
            - name: Rename Windows
              if: contains(matrix.platform.target, 'windows')
              run: |
                cd target/release
                move arrayniac.exe arrayniac-${{matrix.platform.target}}.exe
                cd ../..
            - name: Rename
              if: ${{ !contains(matrix.platform.target, 'windows') }}
              run: |
                cd target/release
                mv arrayniac arrayniac-${{matrix.platform.target}}
                cd ../..
            - name: Upload artifact
              uses: actions/upload-artifact@v4
              with:
                name: arrayniac-${{matrix.platform.target}}${{ contains(matrix.platform.target, 'windows') && '.exe' || '' }}
                path: target/release/arrayniac-${{matrix.platform.target}}${{ contains(matrix.platform.target, 'windows') && '.exe' || '' }}
                overwrite: true
                retention-days: 1


    release:
        permissions:
            contents: write
        needs: [build_matrix]
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Download artifacts
              uses: actions/download-artifact@v4
              with:
                path: ${{github.workspace}}/artifacts
            - name: Release
              uses: softprops/action-gh-release@v2
              with:
                files: |
                  ${{github.workspace}}/artifacts/*/*
